blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Q&A - GitHub Discussions"
    url: https://github.com/track-asia/trackasia-gl-native/discussions/categories/q-a
    about: If you have a question about using TrackAsia GL Native
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://slack.openstreetmap.us/
    about: "Join #trackasia-native on the Open Street Map Slack"

