blank_issues_enabled: true
contact_links:
  - name: "ğŸ™ Q&A - GitHub Discussions"
    url: https://github.com/track-asia-vn/trackasia-native/discussions/categories/q-a
    about: If you have a question about using Trackasia Native
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://slack.openstreetmap.us/
    about: "Join #trackasia-native on the Open Street Map Slack"

